version: '2'
services:
  server:
    image: fikander/jiraadhocanalysis_server:1.0
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - $PWD/notebooks:/notebooks
    env_file:
      - .env
